apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kubevirt-operators
  namespace: openshift-operator-lifecycle-manager
spec:
  sourceType: internal
  configMap: kubevirt-operators
  displayName: KubeVirt Operators
  publisher: Red Hat
