---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cdi-operator
  labels:
    operator.cdi.kubevirt.io: ""
subjects:
- kind: ServiceAccount
  name: cdi-operator
  namespace: cdi
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
